version: '3.7'
services:
    app:
        build:
            context: ./docker/php
            dockerfile: Dockerfile
            args:
                UID: '${UID}'
                GID: '${GID}'
        image: affiliates:latest
        container_name: affiliates-app
        restart: unless-stopped
        working_dir: /app
        volumes:
            - ${SSH_AUTH_SOCK}:${SSH_AUTH_SOCK}
            - ./src:/app
            - ./docker/php/supervisor.ini:/etc/supervisor.d/affiliates.ini
        environment:
            SSH_AUTH_SOCK: ${SSH_AUTH_SOCK}
            # XDEBUG_MODE: debug
        depends_on: [nginx, 'redis', 'mariadb']
        networks:
            - affiliates
    nginx:
        image: nginx:alpine
        container_name: affiliates-www
        restart: unless-stopped
        working_dir: /etc/nginx
        volumes:
            - ./src:/app
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - '${HTTP_PORT:-80}:80'
        networks:
            - affiliates
        # healthcheck:
        #     test: ['CMD', 'nginx', 'ping']
    mariadb:
        image: 'mariadb:latest'
        container_name: affiliates-db
        restart: unless-stopped
        ports:
            - '${DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-docker}'
            MYSQL_DATABASE: '${DB_DATABASE:-affiliates}'
            MYSQL_USER: '${DB_USERNAME:-docker}'
            MYSQL_PASSWORD: '${DB_PASSWORD:-docker}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'affiliates-db:/var/lib/mysql'
        networks:
            - affiliates
        # healthcheck:
        #     test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
        #     retries: 3
        #     timeout: 5s
    redis:
        image: 'redis:alpine'
        container_name: affiliates-redis
        restart: unless-stopped
        ports:
            - '${REDIS_PORT:-6379}:6379'
        volumes:
            - 'affiliates-redis:/data'
        networks:
            - affiliates
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s
    mailhog:
        image: 'mailhog/mailhog:latest'
        container_name: affiliates-mail
        restart: unless-stopped
        ports:
            - '${MAILHOG_SMTP_PORT:-1025}:1025'
            - '${MAILHOG_HTTP_PORT:-8025}:8025'
        networks:
            - affiliates
    # selenium:
    #     image: 'selenium/standalone-chrome'
    #     container_name: affiliates-selenium
    #     restart: unless-stopped
    #     environment:
    #         - JAVA_OPTS=-Dwebdriver.chrome.whitelistedIps=
    #     volumes:
    #         - '/dev/shm:/dev/shm'
    #     networks:
    #         - affiliates

networks:
    affiliates:
        name: affiliates
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.18.0.0/16

volumes:
    affiliates-db:
        name: affiliates-db
        driver: local
    affiliates-redis:
        name: affiliates-redis
        driver: local